settings:
  title: 'Status Page'
  url: 'https://status.viraly.me' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Alle Systeme Online'
  notAllmonitorsOperational: 'System eingeschränkt nutzbar'
  monitorLabelOperational: 'Online'
  monitorLabelNotOperational: 'Offline'
  monitorLabelNoData: 'Keine Daten'
  dayInHistogramNoData: 'Keine Daten'
  dayInHistogramOperational: 'Alles gut'
  dayInHistogramNotOperational: ' Ausfälle' # xx incident(s) recorded

monitors:
  - id: viraly.me # unique identifier
    name: Viraly.me # display name
    description: 'Unser Hauptserver.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: ava-one-vm
    name: 'Ava One'
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true