settings:
  title: 'Server Status'
  url: 'https://status.viraly.me' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'Alle Systeme Online'
  notAllmonitorsOperational: 'System eingeschränkt nutzbar'
  monitorLabelOperational: 'Online'
  monitorLabelNotOperational: 'Offline'
  monitorLabelNoData: 'Keine Daten'
  dayInHistogramNoData: 'Keine Daten'
  dayInHistogramOperational: 'Alles gut'
  dayInHistogramNotOperational: ' Ausfälle' # xx incident(s) recorded

monitors:
  - id: viraly.me # unique identifier
    name: Viraly.me # display name
    description: 'Unsere Website.'# default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: ava-one-vm
    name: 'Ava One'
    description: 'Unser zentrales Rechenzentrum.'
    url: 'https://www.ava-one.viraly.me'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: mail-cloud
    name: 'Mail Server'
    description: 'Unser Mailserver.'
    url: 'https://mail.google.com/mail/'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: meraqi-cloud
    name: 'Meraqi™'
    description: 'Unsere weltweite Deployment-Infrastruktur.'
    url: 'https://cloudflare.com'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: insightsphere-cloud
    name: 'insightSphere™'
    description: 'Unsere Wissensplattform.'
    url: 'https://notion.so'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true